
- name: roadrecon - create project directory for "{{ login_user }}" user
  file:
    path: "{{ login_home }}/roadrecon"
    state: directory
    owner: "{{ login_user }}"
    group: "{{ login_user }}"
    mode: "0755"

- name: roadrecon - create Python virtualenv (runs as "{{ login_user }}")
  command: python3 -m venv "{{ login_home }}"/roadrecon/venv
  args:
    creates: "{{ login_home }}/roadrecon/venv/bin/activate"
  become: yes
  become_user: "{{ login_user }}"

- name: roadrecon - install Roadrecon inside the virtualenv (runs as "{{ login_user }}")
  pip:
    name: roadrecon
    virtualenv: "{{ login_home }}/roadrecon/venv"
    virtualenv_python: python3
    state: latest              # change to “present” if you prefer pinning
  become: yes
  become_user: "{{ login_user }}"

- name: roadrecon - create global wrapper in /usr/local/bin
  file:
    src: "{{ login_home }}/roadrecon/venv/bin/roadrecon"
    dest: /usr/local/bin/roadrecon
    state: link
    force: yes                 # overwrite if link already exists