
- name: BloodHoundCE - create BloodHoundCE directory for {{ login_user }} user
  file:
    path: "{{ login_home }}/BloodHoundCE"
    state: directory
    owner: "{{ login_user }}"
    group: "{{ login_user }}"
    mode: "0755"


# Copy conf files from BloodHound
- name: Copy configuration templates
  template:
    src: "files/bloodHoundCE/{{ item }}"
    dest: "{{ login_home }}/BloodHoundCE/{{ item }}"
    mode: "0664"
  loop:
    - ".env"
    - "bloodhound.config.json"
    - "docker-compose.yml"

- name: BloodHoundCE - add quick reminder read-me
  ansible.builtin.copy:
    dest: "{{ login_home }}/BloodhoundCE_README.txt"
    mode: "0644"
    content: |
      BloodHoundCE docker compose located at {{ login_home }}/BloodHoundCE
      cd {{ login_home }}/BloodHoundCE
      sudo docker compose up -d
      http://localhost:8080/ui/login
      admin:<Initial Password>
  become: yes
  become_user: "{{ login_user }}"

