
- name: bloodhound-python - install/upgrade bloodhound-python via uv
  ansible.builtin.command:
    argv:
      - uv
      - tool
      - install
      - --upgrade
      - bloodhound
  become: yes
  become_user: "{{ login_user }}"
  environment:
    PATH: "{{ login_home }}/.local/bin:{{ ansible_env.PATH | default('') }}"
  tags:
    - bloodhound-python
    - AD

- name: bloodhound-ce-python - install/upgrade bloodhound-ce-python via uv
  ansible.builtin.command:
    argv:
      - uv
      - tool
      - install
      - --upgrade
      - bloodhound-ce
  become: yes
  become_user: "{{ login_user }}"
  environment:
    PATH: "{{ login_home }}/.local/bin:{{ ansible_env.PATH | default('') }}"
  tags:
    - bloodhound-python
    - AD
