
- name: BloodHoundCE - create BloodHoundCE directory for Kali user
  file:
    path: /home/kali/BloodHoundCE
    state: directory
    owner: kali
    group: kali
    mode: "0755"


# Copy conf files from BloodHound
- name: Copy configuration templates
  template:
    src: "files/bloodHoundCE/{{ item }}"
    dest: "/home/kali/BloodHoundCE/{{ item }}"
    mode: "0664"
  loop:
    - ".env"
    - "bloodhound.config.json"
    - "docker-compose.yml"

- name: BloodHoundCE - add quick reminder read-me
  ansible.builtin.copy:
    dest: /home/kali/BloodhoundCE_README.txt
    mode: "0644"
    content: |
      BloodHoundCE docker compose located at ~/BloodHoundCE
      cd ~/BloodHoundCE
      sudo docker compose up -d
      http://localhost:8080/ui/login
      admin:<Initial Password>
  become: yes
  become_user: kali

