- name: kerbrute - Get latest release version
  ansible.builtin.uri:
    url: https://api.github.com/repos/ropnop/kerbrute/releases/latest
    return_content: yes
    follow_redirects: all
  register: kerbrute_release
  tags:
    - kerbrute
    - AD

- name: kerbrute - download & install latest
  ansible.builtin.get_url:
    url: "https://github.com/ropnop/kerbrute/releases/download/{{ kerbrute_release.json.tag_name }}/kerbrute_linux_amd64"
    dest: "/usr/local/bin/kerbrute"
    mode: "0755"
    owner: root
    group: root
    force: true       # always refresh to latest
  tags:
    - kerbrute
    - AD
