
- name: ldapx - install latest release with go install (idempotent)
  ansible.builtin.command: >
    go install github.com/Macmod/ldapx@latest
  args:
    creates: /usr/local/bin/ldapx     # skips rebuild if binary exists
  environment:
    GOBIN: /usr/local/bin            # install straight to system PATH
    GO111MODULE: "on"
