
- name: windapsearch - Ensure installation directory exists
  file:
    path: "/opt/windapsearch"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: windapsearch - Download Windapsearch binary (if missing or outdated)
  get_url:
    url: "https://github.com/ropnop/go-windapsearch/releases/download/v0.3.0/windapsearch-linux-amd64"
    dest: "/opt/windapsearch/windapsearch"
    mode: "0755"
    force: no         # skip download when the file already exists and size/hash match
  register: windap_dl

- name: windapsearch - Create/update symlink in /usr/local/bin
  file:
    src:  "/opt/windapsearch/windapsearch"
    dest: "/usr/local/bin/windapsearch"
    state: link
    owner: root
    group: root
    force: yes        # replaces an old link pointing elsewhere if needed

- name: windapsearch - Verify installation
  command: windapsearch --version
  register: windapsearch_version
  changed_when: false        
  tags: [debug]

- name: windapsearch - Show installed version
  debug:
    msg: "{{ windapsearch_version.stdout }}"
  when: windapsearch_version.stdout is defined
