
- name: impacket - ensure pipx PATH for kali
  become: yes
  become_user: kali
  ansible.builtin.command: python3 -m pipx ensurepath --force
  changed_when: false   # running it twice is harmless; we suppress “changed”

- name: impacket - install/upgrade impacket via pipx
  become: yes
  become_user: kali
  community.general.pipx:
    name: impacket
    state: latest       # upgrades if an older version is present